version: '3.8'

services:
  elvispronda_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=elvispronda_db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydatabase
      - DATABASE_USERNAME=myuser
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - elvispronda_db

  elvispronda_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

volumes:
  postgres_data:

